In [1]:
import numpy as np

In [2]:
ar1=np.array(6)

In [3]:
type(ar1)

numpy.ndarray

In [4]:
ar1

array(6)

In [5]:
ar1=np.array([0,2,1,5])

In [7]:
ar1

array([0, 2, 1, 5])

In [11]:
ar2=np.array([[0,2,1,5],[0,3,0,5]])

In [12]:
ar2

array([[0, 2, 1, 5],
       [0, 3, 0, 5]])

Array Types
1. Zero Array
2. Ones Array
3. Empty Array
4. Array for Range

In [20]:
zero_array=np.zeros((2,1,5))

In [23]:
zero_array

array([[[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]]])

In [26]:
ones_array=np.ones((2,2,2))

In [27]:
ones_array

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [28]:
ar4=np.arange(2,15,2)

In [29]:
ar4

array([ 2,  4,  6,  8, 10, 12, 14])

In [30]:
ar6=np.transpose(ar2)

In [33]:
ar6

array([[0, 0],
       [2, 3],
       [1, 0],
       [5, 5]])

In [34]:
ar7=np.ravel(ar6)

In [35]:
ar7

array([0, 0, 2, 3, 1, 0, 5, 5])

In [41]:
a1=np.array([0,2])
a2=np.array([1,5])

In [42]:
a1

array([0, 2])

In [43]:
a2

array([1, 5])

In [44]:
concat=np.concatenate((a1,a2))

In [45]:
concat

array([0, 2, 1, 5])

In [46]:
hori=np.hstack((a1,a2))

In [47]:
hori

array([0, 2, 1, 5])

In [48]:
vert=np.vstack((a1,a2))

In [49]:
vert

array([[0, 2],
       [1, 5]])