In [42]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [43]:
import numpy as np

In [44]:
mat1 = np.array([[2, 6], [6, 11]])

In [45]:
mat1

array([[ 2,  6],
       [ 6, 11]])

In [46]:
mat2 = np.array([[2, 6, 3], [6, 11, 4], [17, 2, 73]])

In [47]:
mat2

array([[ 2,  6,  3],
       [ 6, 11,  4],
       [17,  2, 73]])

In [48]:
det_df_mat1=np.linalg.det(mat1)

In [49]:
det_df_mat1

-14.000000000000004

In [50]:
det_df_mat2=np.linalg.det(mat2)

In [51]:
det_df_mat2

-1154.9999999999998

In [52]:
inverse=np.linalg.inv(mat2)

In [53]:
inverse

array([[-0.68831169,  0.37402597,  0.00779221],
       [ 0.32034632, -0.08225108, -0.00865801],
       [ 0.15151515, -0.08484848,  0.01212121]])

In [54]:
dense = np.array([[2, 6, 3,2], [6, 11, 4,6], [17, 2, 73,17],[2, 6, 3,2]])

In [55]:
dense 

array([[ 2,  6,  3,  2],
       [ 6, 11,  4,  6],
       [17,  2, 73, 17],
       [ 2,  6,  3,  2]])

In [56]:
from scipy.sparse import csr_matrix

In [57]:
sparse=csr_matrix(dense)

In [58]:
sparse

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 16 stored elements and shape (4, 4)>

In [59]:
print(sparse)

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 16 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	2
  (0, 1)	6
  (0, 2)	3
  (0, 3)	2
  (1, 0)	6
  (1, 1)	11
  (1, 2)	4
  (1, 3)	6
  (2, 0)	17
  (2, 1)	2
  (2, 2)	73
  (2, 3)	17
  (3, 0)	2
  (3, 1)	6
  (3, 2)	3
  (3, 3)	2
